version: "3.9"
services:
  app:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      TZ: Asia/Jakarta
      ENABLE_SCHEDULER: "true"
    volumes:
      - ./data:/app/data
      - ./config:/app/config
