name: Hourly IDX Automation

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Fetch hourly quotes
        run: python -m automation.fetch_quotes

      - name: Calculate daily indicators
        run: python -m automation.calculate_indicators

      - name: Commit updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/*.csv data/snapshots/*.csv logs/
          git commit -m "Auto update: $(date '+%Y-%m-%d %H:%M:%S')" || echo "No changes"
          git push
